# Generated by Django 4.2.9 on 2024-02-08 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='Об автомобиле')),
                ('car_photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Gearboxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.CharField(db_index=True, verbose_name='Коробка передач')),
                ('wd', models.CharField(choices=[('FWD', 'Передний'), ('RWD', 'Задний'), ('AWD', 'Полный')], default=('FWD', 'Передний'), max_length=3, verbose_name='Привод')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Generations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(db_index=True, max_length=50, verbose_name='Модель')),
                ('gen', models.CharField(max_length=50, verbose_name='Поколение')),
                ('body', models.CharField(choices=[('HT3', 'Хэтчбек 3дв.'), ('HT5', 'Хэтчбек 5дв.'), ('SD4', 'Седан 4дв.'), ('UV5', 'Универсал 5дв.'), ('SV5', 'Внедорожник 5дв.'), ('CU2', 'Купэ 2дв.'), ('CB2', 'Кабриолет 2дв.')], max_length=3, verbose_name='Тип кузова')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, verbose_name='Объявление')),
                ('time_shared', models.DateTimeField(auto_now=True, verbose_name='Время размещения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.cars')),
            ],
        ),
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(choices=[('PT', 'Бензин'), ('DT', 'Дизель'), ('HB', 'Гибрид')], default=('PT', 'Бензин'), max_length=2, verbose_name='Тип двигателя')),
                ('engine', models.CharField(db_index=True, verbose_name='Двигатель')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.gearboxes')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.generations')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_recomm', models.BooleanField(default=True, verbose_name='Получать рекомендации')),
                ('my_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('users_photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото от пользователя')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.gearboxes'),
        ),
        migrations.AddField(
            model_name='cars',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.motors'),
        ),
        migrations.AddField(
            model_name='cars',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.generations', verbose_name='Модель'),
        ),
    ]
