# Generated by Django 4.2.9 on 2024-02-15 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=20, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'тип кузова',
                'verbose_name_plural': 'Типы кузова',
            },
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(db_index=True, max_length=50, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'модель Audi',
                'verbose_name_plural': 'Модели Audi',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='Об автомобиле')),
                ('car_photo', models.ImageField(upload_to='car_photos/%Y/%m/%d/', verbose_name='Фото автомобиля')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.bodytypes', verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='FuelTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(default='Бензин', max_length=10, verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'тип топлива',
                'verbose_name_plural': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='Gearboxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear', models.CharField(default='Механика', max_length=10, verbose_name='Коробка передач')),
            ],
            options={
                'verbose_name': 'коробку передач',
                'verbose_name_plural': 'Коробки передач',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Generations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.CharField(max_length=50, verbose_name='Поколение')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.carmodels', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Поколения автомобилей',
                'verbose_name_plural': 'Поколения автомобилей',
            },
        ),
        migrations.CreateModel(
            name='WheelDrives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd', models.CharField(default='Передний', max_length=10, verbose_name='Привод')),
            ],
            options={
                'verbose_name': 'тип привода',
                'verbose_name_plural': 'Типы привода',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, verbose_name='Объявление')),
                ('url_photo', models.ImageField(upload_to='url_photos/%Y/%m/%d/', verbose_name='Фото объявления')),
                ('shared_time', models.DateTimeField(auto_now=True, verbose_name='Время размещения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.cars')),
            ],
            options={
                'verbose_name': 'Рекомендации',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(db_index=True, verbose_name='Двигатель')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.generations', verbose_name='Поколение')),
            ],
            options={
                'verbose_name': 'Двигатели',
                'verbose_name_plural': 'Двигатели',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_recomm', models.BooleanField(default=True, verbose_name='Получать рекомендации')),
                ('my_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Гараж',
                'verbose_name_plural': 'Гараж',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('user_photo', models.ImageField(upload_to='user_photos/%Y/%m/%d/', verbose_name='Фото от пользователя')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.fueltypes', verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='cars',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.gearboxes', verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='cars',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.generations', verbose_name='Поколение'),
        ),
        migrations.AddField(
            model_name='cars',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.motors', verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='cars',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.carmodels', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='cars',
            name='wheel_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiapi.wheeldrives', verbose_name='Привод'),
        ),
    ]
