# Generated by Django 4.2.9 on 2024-02-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodels',
            options={'ordering': ['car_name'], 'verbose_name': 'модель Audi', 'verbose_name_plural': 'Модели Audi'},
        ),
        migrations.AlterModelOptions(
            name='generations',
            options={'verbose_name': 'поколение', 'verbose_name_plural': 'Поколения'},
        ),
        migrations.AlterModelOptions(
            name='motors',
            options={'verbose_name': 'двигатель', 'verbose_name_plural': 'Двигатели'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_photo',
            field=models.ImageField(blank=True, upload_to='car_photos/%Y/%m/%d/', verbose_name='Фото автомобиля'),
        ),
    ]
