# Generated by Django 4.2.9 on 2024-05-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiapi', '0005_alter_recommendations_url_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='shared_time',
            field=models.CharField(blank=True, verbose_name='Время размещения'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='url_photo',
            field=models.TextField(blank=True, verbose_name='Фото объявления'),
        ),
    ]
