# Generated by Django 4.2.9 on 2024-05-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiapi', '0006_alter_recommendations_shared_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='url_photo',
            field=models.TextField(blank=True, null=True, verbose_name='Фото объявления'),
        ),
    ]
