# Generated by Django 4.2.9 on 2024-05-28 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiapi', '0007_alter_recommendations_url_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания записи'),
            preserve_default=False,
        ),
    ]
