# Generated by Django 4.2.9 on 2024-07-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiapi', '0008_recommendations_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytypes',
            name='drom_body',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип кузова для Drom'),
        ),
    ]
